---
- hosts: web
  tasks:
    - name: get uptime
      shell: uptime |awk '{printf("%.2f",$(NF-2))}'
      register: result
    - name: shutdown httpd
      service:
        name: httpd
        state: stopped
      when: result.stdout|float > 0.7
    - debug: var=result
